# From https://devkitpro.org/wiki/Getting_Started/devkitARM
language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Stuff
  - pwd
  - my_github=${PWD##*/} 
  - echo $my_github
  - sudo ./build_libnds_64

script:
  - export DEVKITPRO=/opt/devkitpro
  - export DEVKITARM=$DEVKITPRO/devkitARM
  # Do not call qmake, this will not work
  - cd ~/build/richelbilderbeek/$my_github
  - ./build_music
  - make
  - if [[ -f libnds_example_2.nds ]]; then echo "YES :-)"; else echo "NO :-("; fi

